### ISSUE TITLE
Disconnecting during a match causes your ball to not move when you hit it

### ISSUE THREAD

**Issue by VideoGameSmash12** [jaylawl/Jaygrounds#16]
**Describe the bug**
When you are in a match, if you disconnect and then reconnect for any reason, your ball will simply not move when try to hit it.

**To Reproduce**
1. Start or join a match
2. Disconnect and then reconnect

**Expected behavior**
The ball to move when you hit it.

**Screenshots**
https://cdn.discordapp.com/attachments/877302138538180658/942747130861342730/javaw_f3IG73x6ta.mp4

**Additional context**
Disconnecting and waiting 90 seconds before reconnecting seems to resolve the problem.

**Comment by jaylawl** [comment]
That's a very good find, i'll get onto that asap.
Appreciate the video, that made it very easy to understand the problem. Thanks!

**Comment by jaylawl** [comment]
I am unable to reproduce this error in the current dev-state of the golf plugin, and there have been 100+ commits since the last public patch. Thus i won't be able to pinpoint when this stopped happening.

I am assuming this fixed for the upcoming patch. Please re-open or re-post this issue if it should occurr again
